[build-system]
requires = ["uv_build>=0.11.0,<1.0.0"]
build-backend = "uv_build"

[project]
name = "groundtruth"
description = "Ground Truth Analysis Tooling"
license = "MIT"
readme = "README.md"
requires-python = ">=3.10,<4"
version = "3.0.0"
dependencies = [
    "aiometer (>=1.0.0,<2.0.0)",
    "arguably (>=1.3.0,<2.0.0)",
    "indico-client (>=6.14.1,<7.0.0)",
    "indico-toolkit (>=7.2.2,<8.0.0)",
    "munkres (>=1.1.4,<2.0.0)",
    "pathvalidate (>=3.3.1,<4.0.0)",
    "polars (>=1.35.2,<2.0.0)",
    "rapidfuzz (>=3.14.3,<4.0.0)",
    "rich (>=14.2.0,<15.0.0)",
]

[dependency-groups]
dev = [
    "coverage (>=7.0.0)",
    "poethepoet (>=0.30.0)",
    "pytest-asyncio (>=1.0.0)",
    "pytest-cov (>=7.0.0)",
    "pytest-mock (>=3.0.0)",
    "pytest (>=9.0.0)",
    "ruff (>=0.15.0)",
    "ty (>=0.0.50)",
]

[project.scripts]
groundtruth = "groundtruth.cli:main"

[tool.poe.tasks]
coverage = "coverage html"
pytest = "pytest tests --cov=src --cov=tests"
ruff-check = "ruff check src tests"
ruff-fix = "ruff check --fix-only src tests"
ruff-format = "ruff format src tests"
ruff-format-check = "ruff format --check src tests"
ty = "ty check src tests"
ty-fix = "ty check --fix src tests"

format = ["ruff-fix", "ruff-format"]
check = ["ruff-check", "ruff-format-check", "ty"]
test = ["pytest", "coverage"]
all = ["format", "check", "test"]

[tool.ruff]
line-length = 88
lint.select = ["E", "F", "I"]
lint.fixable = ["I"]

[tool.ty.src]
exclude = ["indico", "munkres"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

[tool.coverage.run]
branch = true

[tool.coverage.report]
exclude_lines = ["pragma: no cover", "@abstractmethod"]
