name: Python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Python:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - name: Checkout Commit
      uses: actions/checkout@v4

    - name: Install Poetry
      run: pipx install "poetry>=2,<3"

    - name: Install Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: "poetry"

    - name: Install Dependencies
      run: |
        poetry env use ${{ matrix.python-version }}
        poetry install

    - name: Run Black
      run: poetry poe black-check

    - name: Run Ruff
      run: poetry poe ruff-check

    - name: Run Mypy
      run: poetry poe mypy

    - name: Run Pytest
      run: poetry poe pytest
