name: Python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Python:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - name: Checkout Commit
      uses: actions/checkout@v3

    - name: Install Poetry
      run: pipx install "poetry>=1.2.2,<2"

    - name: Install Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: "poetry"

    - name: Install Dependencies
      run: |
        poetry env use ${{ matrix.python-version }}
        poetry install

    - name: Run Black
      run: poetry run poe black_check

    - name: Run Ruff
      run: poetry run poe ruff

    - name: Run Mypy
      run: poetry run poe mypy

    - name: Run Pytest
      run: poetry run poe pytest
